"""add phone number

Revision ID: 266e4d1ce354
Revises: a8c3ef41103b
Create Date: 2023-02-11 13:12:15.815978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '266e4d1ce354'
down_revision = 'a8c3ef41103b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
